window.STATE_DATA = [
  {id:"01",name:"Alabama",abbr:"AL",capital:"Montgomery",region:"Southeast"},
  {id:"02",name:"Alaska",abbr:"AK",capital:"Juneau",region:"West"},
  {id:"04",name:"Arizona",abbr:"AZ",capital:"Phoenix",region:"Southwest"},
  {id:"05",name:"Arkansas",abbr:"AR",capital:"Little Rock",region:"Southeast"},
  {id:"06",name:"California",abbr:"CA",capital:"Sacramento",region:"West"},
  {id:"08",name:"Colorado",abbr:"CO",capital:"Denver",region:"West"},
  {id:"09",name:"Connecticut",abbr:"CT",capital:"Hartford",region:"New England"},
  {id:"10",name:"Delaware",abbr:"DE",capital:"Dover",region:"Mid-Atlantic"},
  {id:"12",name:"Florida",abbr:"FL",capital:"Tallahassee",region:"Southeast"},
  {id:"13",name:"Georgia",abbr:"GA",capital:"Atlanta",region:"Southeast"},
  {id:"15",name:"Hawaii",abbr:"HI",capital:"Honolulu",region:"West"},
  {id:"16",name:"Idaho",abbr:"ID",capital:"Boise",region:"West"},
  {id:"17",name:"Illinois",abbr:"IL",capital:"Springfield",region:"Midwest"},
  {id:"18",name:"Indiana",abbr:"IN",capital:"Indianapolis",region:"Midwest"},
  {id:"19",name:"Iowa",abbr:"IA",capital:"Des Moines",region:"Midwest"},
  {id:"20",name:"Kansas",abbr:"KS",capital:"Topeka",region:"Midwest"},
  {id:"21",name:"Kentucky",abbr:"KY",capital:"Frankfort",region:"Southeast"},
  {id:"22",name:"Louisiana",abbr:"LA",capital:"Baton Rouge",region:"Southeast"},
  {id:"23",name:"Maine",abbr:"ME",capital:"Augusta",region:"New England"},
  {id:"24",name:"Maryland",abbr:"MD",capital:"Annapolis",region:"Mid-Atlantic"},
  {id:"25",name:"Massachusetts",abbr:"MA",capital:"Boston",region:"New England"},
  {id:"26",name:"Michigan",abbr:"MI",capital:"Lansing",region:"Midwest"},
  {id:"27",name:"Minnesota",abbr:"MN",capital:"Saint Paul",region:"Midwest"},
  {id:"28",name:"Mississippi",abbr:"MS",capital:"Jackson",region:"Southeast"},
  {id:"29",name:"Missouri",abbr:"MO",capital:"Jefferson City",region:"Midwest"},
  {id:"30",name:"Montana",abbr:"MT",capital:"Helena",region:"West"},
  {id:"31",name:"Nebraska",abbr:"NE",capital:"Lincoln",region:"Midwest"},
  {id:"32",name:"Nevada",abbr:"NV",capital:"Carson City",region:"West"},
  {id:"33",name:"New Hampshire",abbr:"NH",capital:"Concord",region:"New England"},
  {id:"34",name:"New Jersey",abbr:"NJ",capital:"Trenton",region:"Mid-Atlantic"},
  {id:"35",name:"New Mexico",abbr:"NM",capital:"Santa Fe",region:"Southwest"},
  {id:"36",name:"New York",abbr:"NY",capital:"Albany",region:"Mid-Atlantic"},
  {id:"37",name:"North Carolina",abbr:"NC",capital:"Raleigh",region:"Southeast"},
  {id:"38",name:"North Dakota",abbr:"ND",capital:"Bismarck",region:"Midwest"},
  {id:"39",name:"Ohio",abbr:"OH",capital:"Columbus",region:"Midwest"},
  {id:"40",name:"Oklahoma",abbr:"OK",capital:"Oklahoma City",region:"Southwest"},
  {id:"41",name:"Oregon",abbr:"OR",capital:"Salem",region:"West"},
  {id:"42",name:"Pennsylvania",abbr:"PA",capital:"Harrisburg",region:"Mid-Atlantic"},
  {id:"44",name:"Rhode Island",abbr:"RI",capital:"Providence",region:"New England"},
  {id:"45",name:"South Carolina",abbr:"SC",capital:"Columbia",region:"Southeast"},
  {id:"46",name:"South Dakota",abbr:"SD",capital:"Pierre",region:"Midwest"},
  {id:"47",name:"Tennessee",abbr:"TN",capital:"Nashville",region:"Southeast"},
  {id:"48",name:"Texas",abbr:"TX",capital:"Austin",region:"Southwest"},
  {id:"49",name:"Utah",abbr:"UT",capital:"Salt Lake City",region:"West"},
  {id:"50",name:"Vermont",abbr:"VT",capital:"Montpelier",region:"New England"},
  {id:"51",name:"Virginia",abbr:"VA",capital:"Richmond",region:"Southeast"},
  {id:"53",name:"Washington",abbr:"WA",capital:"Olympia",region:"West"},
  {id:"54",name:"West Virginia",abbr:"WV",capital:"Charleston",region:"Southeast"},
  {id:"55",name:"Wisconsin",abbr:"WI",capital:"Madison",region:"Midwest"},
  {id:"56",name:"Wyoming",abbr:"WY",capital:"Cheyenne",region:"West"}
];

window.DEFAULT_POEMS = [{
  id:"brave-little-steps",
  title:"Brave Little Steps",
  author:"Asher's Learning Arcade",
  text:"A little step, a little try,\nA question asked: how, when, and why?\nI do not need to know it all—\nI learn each time I rise from a fall.\n\nWith every word and fact I find,\nI build a brave and growing mind."
}];

